### ISSUE TITLE
Make "eco" mode optional based on firmware version

### ISSUE THREAD

**Issue by Jalle19** [Jalle19/eda-modbus-bridge#104]
Many units don't have this mode.

**Comment by Jalle19** [comment]
@juntta do you have an "eco" mode on your unit?

**Comment by juntta** [comment]
I used to have but when updated the firmware to support tcp connection, it was gone!

**Comment by ssalmela** [comment]
> My own notes regarding software versions:
> 
> 2.17 pingvin eco ede 1.42 eair md juntta 1.18 ede ewind 2.01 wanha 5.54 pandion eda 1.97 elmis old ltr-6 eco ede

Perhaps the Wanha is also too old to remember anything and refuses write operations via Freeway connector. 

Any idea if firmware can be flashed to newer version? (I did already send the question to Enervent support/maintenance)

**Comment by juntta** [comment]
> > My own notes regarding software versions:
> 
> > 
> 
> > 2.17 pingvin eco ede 1.42 eair md juntta 1.18 ede ewind 2.01 wanha 5.54 pandion eda 1.97 elmis old ltr-6 eco ede
> 
> 
> 
> Perhaps the Wanha is also too old to remember anything and refuses write operations via Freeway connector. 
> 
> 
> 
> Any idea if firmware can be flashed to newer version? (I did already send the question to Enervent support/maintenance)

At least Pelican model is upgradable. I had to flash firmware to support TCP connection which was possible with newer firmware.
