### ISSUE TITLE
Make HTTP service optional

### ISSUE THREAD

**Issue by tomrosenback** [Jalle19/eda-modbus-bridge#17]
In Home Assistant HTTP is not needed as everything is handled through MQTT. Make the parameter optional and disable HTTP endpoints if not provided.

**Comment by Jalle19** [comment]
Good idea

**Comment by Jalle19** [comment]
I personally use the HTTP in combination with https://github.com/Jalle19/eda-influxdb to store the readings in InfluxDB. Now that there's MQTT support this could be done differently, but I guess the work is already done so no point in changing it anymore.

**Comment by tomrosenback** [comment]
Yes I figured you did so. Oh that makes me realize that I removed the HTTP ports from the config.json, which will as it stands break any HTTP calls. Can add that back.

**Comment by Jalle19** [comment]
> Can add that back.

Please do :D

**Comment by tomrosenback** [comment]
Did already :D
