### ISSUE TITLE
Add authentication to MQTT client

### ISSUE THREAD

**Issue by tomrosenback** [Jalle19/eda-modbus-bridge#18]
Make MQTT client use credentials provided with options.

**Comment by Jalle19** [comment]
I'll use `--mqttUser` and `--mqttPassword` like you've already done here: https://github.com/Jalle19/home-assistant-addon-repository/blob/main/eda-modbus-bridge/config.sh#L45

**Comment by tomrosenback** [comment]
Yep, those are just preparation for the credentials, if you feel the naming should be changed, go ahead, will not break anything, yet.
