### ISSUE TITLE
Expose device information over MQTT as well

### ISSUE THREAD

**Issue by Jalle19** [Jalle19/eda-modbus-bridge#19]
This would bring feature parity to the MQTT and HTTP APIs

**Comment by tomrosenback** [comment]
Which specific device information would you like to see in? And where?

**Comment by Jalle19** [comment]
These values:

```
eda/deviceInformation/fanType "EC"
eda/deviceInformation/coolingTypeInstalled null
eda/deviceInformation/heatingTypeInstalled "EDE"
eda/deviceInformation/familyType "Pingvin"
eda/deviceInformation/serialNumber 0
eda/deviceInformation/softwareVersion 2.17
```

**Comment by Jalle19** [comment]
Maybe these should be published _once_ with retain set? I'm not that familiar with MQTT yet so I'm not sure if it's desirable here.

**Comment by tomrosenback** [comment]
Maybe, question is what they are needed for as the information is shown in the Device info box and is already part of the device information in the discovery?
