### ISSUE TITLE
Discovery messages should be retained

### ISSUE THREAD

**Issue by tomrosenback** [Jalle19/eda-modbus-bridge#29]
The discovery messages sent to the home assistant topic should have the retain flag sent to true, otherwise the entities will remain unavailable until next set of discovery messages are published after a reboot of HA.

**Comment by Jalle19** [comment]
Sounds reasonable, I read about it but didn't really understand the issue.

**Comment by tomrosenback** [comment]
Yes, I have already experienced the unavailability of the entities due to the not retained messages.
