### ISSUE TITLE
Add support for 3x0001, 3x0003 and 3x0004 holding registers

### ISSUE THREAD

**Issue by Ta802** [Jalle19/eda-modbus-bridge#96]
Could there be a possibility to add different modbus registers to be shown through addon?

Pingvin MDE eAir has holding register "1" (Room temperature sensor TE20) and "4" (Current exhaust fan speed) which I would be interested to get data from. Is there a way to make this possible while not breaking addon for others using different models.

eAir modbus register list can be found here: https://doc.enervent.com/out/out.ViewFolder.php?folderid=16&showtree=1

**Comment by Jalle19** [comment]
Moved the issue to the correct repository

**Comment by Jalle19** [comment]
@juntta can you test this branch and see if you get any values for supply and exhaust fan speeds (holding registers 3 and 4)?

**Comment by juntta** [comment]
> @juntta can you test this branch and see if you get any values for supply and exhaust fan speeds (holding registers 3 and 4)?

Ok, I'll try to test it out this weekend!

**Comment by Jalle19** [comment]
https://github.com/Jalle19/eda-modbus-bridge/pull/97 here, `more-sensors`

**Comment by juntta** [comment]
Sorry, got sick last weekend:

![image](https://github.com/Jalle19/eda-modbus-bridge/assets/39326510/ed348267-772f-4a06-987b-0a35feca0e5d)

**Comment by Jalle19** [comment]
What firmware veesion do you have?

**Comment by juntta** [comment]
Software version from the integration shows 1.42. Is that what you meant? The eAir software version is 2.14.

**Comment by Jalle19** [comment]
Thanks!
